# Generated by Django 5.0.2 on 2024-03-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
