# Generated by Django 5.0.1 on 2024-02-14 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_customuser_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courts',
            new_name='Court',
        ),
    ]
