# Generated by Django 5.0.2 on 2024-04-05 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='courttypet',
            name='court_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courttype'),
        ),
    ]
