# Generated by Django 5.0.1 on 2024-02-14 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_courts_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='price_per_hour',
            field=models.IntegerField(null=True),
        ),
    ]
