# Generated by Django 5.0.1 on 2024-02-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_court_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='offer_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='offer_price_per_hour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='offer_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
