# Generated by Django 5.0.2 on 2024-04-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_courtcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtcustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='courtcustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
