# Generated by Django 5.0.2 on 2024-04-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_courtcustomer_created_at_courtcustomer_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtcustomer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='courtcustomer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
