# Generated by Django 5.0.1 on 2024-02-14 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_court_location_court_lang_court_lat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='lang',
        ),
        migrations.RemoveField(
            model_name='court',
            name='lat',
        ),
        migrations.AddField(
            model_name='court',
            name='location',
            field=models.URLField(null=True),
        ),
    ]
