# Generated by Django 5.0.2 on 2024-04-06 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_courtcustomer_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='number',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/numbers/'),
        ),
        migrations.AddField(
            model_name='number',
            name='name',
            field=models.CharField(max_length=155, null=True),
        ),
    ]
