# Generated by Django 5.0.1 on 2024-02-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_date_to',
            field=models.DateField(null=True),
        ),
    ]
