# Generated by Django 5.0.1 on 2024-02-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_book_book_date_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_date_to',
        ),
    ]
