# Generated by Django 5.0.2 on 2024-04-06 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_number_address_alter_number_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='number',
            name='name',
            field=models.CharField(max_length=155),
        ),
    ]
