# Generated by Django 5.0.1 on 2024-02-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_booksetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
