# Generated by Django 5.0.2 on 2024-04-07 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_courtadditionaltool_court_additional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtadditional',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_court', to='api.court', unique=True),
        ),
    ]
