# Generated by Django 5.0.1 on 2024-02-16 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_courtadditional_courtadditionaltool'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksetting',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='api.courtadditionaltool'),
        ),
    ]
