# Generated by Django 5.0.1 on 2024-02-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_booksetting_tools'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_from',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_to',
        ),
        migrations.CreateModel(
            name='BookTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_from', models.TimeField()),
                ('book_to', models.TimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.book')),
            ],
        ),
    ]
