# Generated by Django 5.0.1 on 2024-02-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_book_book_from_remove_book_book_to_booktime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booktime',
            name='book',
        ),
        migrations.AddField(
            model_name='book',
            name='times',
            field=models.ManyToManyField(null=True, to='api.booktime'),
        ),
    ]
