# Generated by Django 5.0.1 on 2024-02-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_booktime_book_book_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='times',
        ),
        migrations.AddField(
            model_name='booktime',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.book'),
        ),
        migrations.AlterField(
            model_name='booktime',
            name='book_from',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booktime',
            name='book_to',
            field=models.TimeField(null=True),
        ),
    ]
