# Generated by Django 5.0.1 on 2024-02-16 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_book_times_booktime_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktime',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_time', to='api.book'),
        ),
    ]
