# Generated by Django 5.0.1 on 2024-02-18 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_booktime_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='close',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='court',
            name='location',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='open',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='price_per_hour',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='court',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state'),
        ),
        migrations.AlterField(
            model_name='court',
            name='title',
            field=models.CharField(max_length=155),
        ),
        migrations.AlterField(
            model_name='court',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
