# Generated by Django 5.0.1 on 2024-02-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_court_close_alter_court_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksetting',
            name='book_to',
        ),
        migrations.AddField(
            model_name='booktime',
            name='book_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
