# Generated by Django 5.0.1 on 2024-02-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_booksetting_book_to_booktime_book_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='court',
        ),
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.RemoveField(
            model_name='booksetting',
            name='book',
        ),
        migrations.RemoveField(
            model_name='booksetting',
            name='tools',
        ),
        migrations.RemoveField(
            model_name='court',
            name='state',
        ),
        migrations.RemoveField(
            model_name='court',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courtadditional',
            name='court',
        ),
        migrations.RemoveField(
            model_name='courtadditional',
            name='user',
        ),
        migrations.RemoveField(
            model_name='courtadditionaltool',
            name='court_additional',
        ),
        migrations.DeleteModel(
            name='BookTime',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookSetting',
        ),
        migrations.DeleteModel(
            name='Court',
        ),
        migrations.DeleteModel(
            name='CourtAdditional',
        ),
        migrations.DeleteModel(
            name='CourtAdditionalTool',
        ),
    ]
