# Generated by Django 5.0.1 on 2024-02-21 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_book_court_remove_book_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('price_per_hour', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
                ('location', models.URLField()),
                ('offer_price_per_hour', models.IntegerField(blank=True, null=True)),
                ('offer_from', models.TimeField(blank=True, null=True)),
                ('offer_to', models.TimeField(blank=True, null=True)),
                ('with_ball', models.BooleanField(default=True, null=True)),
                ('ball_price', models.IntegerField(blank=True, null=True)),
                ('event', models.BooleanField(default=False, null=True)),
                ('event_price', models.IntegerField(blank=True, null=True)),
                ('event_from', models.TimeField(blank=True, null=True)),
                ('event_to', models.TimeField(blank=True, null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.state')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourtAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.court')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourtAdditionalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('court_additional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courtadditional')),
            ],
        ),
    ]
