# Generated by Django 5.0.1 on 2024-02-21 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_court_courtadditional_courtadditionaltool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtadditional',
            name='user',
        ),
    ]
