# Generated by Django 5.0.1 on 2024-02-21 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_remove_courtadditional_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtadditional',
            name='court',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_court', to='api.court'),
        ),
    ]
