# Generated by Django 5.0.1 on 2024-02-21 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_courtadditional_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtadditionaltool',
            name='court_additional',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tools_court', to='api.courtadditional'),
        ),
    ]
