# Generated by Django 5.0.1 on 2024-02-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_courttype_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.courttype'),
        ),
    ]
