# Generated by Django 5.0.1 on 2024-02-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_court_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='closed_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='closed_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
