# Generated by Django 5.0.1 on 2024-02-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_court_closed_from_court_closed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='closed_now',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
