# Generated by Django 5.0.1 on 2024-02-23 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_remove_courttype_user_remove_state_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courts/images/')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_image', to='api.court')),
            ],
        ),
        migrations.CreateModel(
            name='CourtVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_video', to='api.court')),
            ],
        ),
    ]
