# Generated by Django 5.0.1 on 2024-02-23 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_courtimage_courtvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='image',
        ),
    ]
