# Generated by Django 5.0.2 on 2024-02-24 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_court_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=155)),
                ('if_free', models.BooleanField()),
                ('coast', models.IntegerField()),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_features', to='api.court')),
            ],
        ),
    ]
