# Generated by Django 5.0.2 on 2024-02-24 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_courtfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtfeature',
            name='coast',
        ),
        migrations.AddField(
            model_name='courtfeature',
            name='if_available',
            field=models.BooleanField(null=True),
        ),
    ]
