# Generated by Django 5.0.2 on 2024-02-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_remove_courtfeature_coast_courtfeature_if_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtfeature',
            name='if_available',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='courtfeature',
            name='if_free',
            field=models.BooleanField(default=False),
        ),
    ]
