# Generated by Django 5.0.2 on 2024-02-24 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_courtfeature_if_available_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtfeature',
            old_name='if_available',
            new_name='is_available',
        ),
    ]
