# Generated by Django 5.0.2 on 2024-02-25 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_rename_if_available_courtfeature_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courtfeature',
            old_name='if_free',
            new_name='is_free',
        ),
    ]
