# Generated by Django 5.0.2 on 2024-02-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_rename_if_free_courtfeature_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='paied',
            field=models.CharField(choices=[('E_Wallet', 'E_Wallet'), ('Cash', 'Cash')], max_length=155, null=True),
        ),
    ]
