# Generated by Django 5.0.2 on 2024-02-25 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_book_paied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='paied',
            field=models.CharField(choices=[('E_Wallet', 'E_Wallet'), ('Cash', 'Cash')], max_length=155),
        ),
    ]
