# Generated by Django 5.0.2 on 2024-02-26 08:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_book_paied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='type',
        ),
        migrations.AddField(
            model_name='court',
            name='type',
            field=models.ManyToManyField(null=True, related_name='court_types', to=settings.AUTH_USER_MODEL),
        ),
    ]
