# Generated by Django 5.0.2 on 2024-02-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_remove_court_type_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ManyToManyField(null=True, related_name='court_types', to='api.courttype'),
        ),
    ]
