# Generated by Django 5.0.2 on 2024-02-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_court_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='type',
            field=models.ManyToManyField(blank=True, null=True, related_name='court_types', to='api.courttype'),
        ),
    ]
