# Generated by Django 5.0.2 on 2024-02-26 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_court_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='type',
        ),
        migrations.AddField(
            model_name='court',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.courttype'),
        ),
    ]
