# Generated by Django 5.0.2 on 2024-02-28 09:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_customuser_staff_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff_with',
        ),
        migrations.AddField(
            model_name='customuser',
            name='staffs',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
