# Generated by Django 5.0.2 on 2024-02-28 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_remove_customuser_staff_with_customuser_staffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staffs',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
