# Generated by Django 5.0.2 on 2024-02-28 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_customuser_staff_with_alter_customuser_staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff_with',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staffs',
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
