# Generated by Django 5.0.2 on 2024-02-28 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_remove_customuser_staff_with_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
