# Generated by Django 5.0.2 on 2024-02-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_customuser_staff_with_customuser_staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='staff_with',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='staffs',
        ),
    ]
