# Generated by Django 5.0.2 on 2024-02-28 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_remove_customuser_staff_with_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='staff_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
