# Generated by Django 5.0.2 on 2024-02-28 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_customuser_staff_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='staff_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_for_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
