# Generated by Django 5.0.2 on 2024-02-28 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_alter_customuser_staff_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_court', to=settings.AUTH_USER_MODEL),
        ),
    ]
