# Generated by Django 5.0.2 on 2024-02-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_court_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_paied',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
