# Generated by Django 5.0.2 on 2024-02-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_book_is_paied'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='total_mony',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
