# Generated by Django 5.0.2 on 2024-02-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_setting_total_mony'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setting',
            old_name='total_mony',
            new_name='total_money',
        ),
        migrations.AddField(
            model_name='setting',
            name='waiting_money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
