# Generated by Django 5.0.2 on 2024-03-02 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_number_setting_cancel_time_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='numbers',
        ),
        migrations.AddField(
            model_name='number',
            name='setting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.setting'),
        ),
    ]
