# Generated by Django 5.0.2 on 2024-03-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_remove_setting_numbers_number_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='with_ball',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
