# Generated by Django 5.0.2 on 2024-03-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_alter_court_with_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_cancelled',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
