# Generated by Django 5.0.2 on 2024-03-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_book_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cancelled_money',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
