# Generated by Django 5.0.2 on 2024-03-05 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_court_ball_price_alter_court_event_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='book',
        ),
        migrations.AddField(
            model_name='notification',
            name='book_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.booktime'),
        ),
    ]
