# Generated by Django 5.0.2 on 2024-03-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_remove_notification_book_notification_book_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_sent',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
