# Generated by Django 5.0.2 on 2024-03-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0077_remove_book_event_remove_book_is_cancelled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktime',
            old_name='book_to_date_cancel',
            new_name='is_cancelled_day',
        ),
    ]
