# Generated by Django 5.0.2 on 2024-03-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0078_rename_book_to_date_cancel_booktime_is_cancelled_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktime',
            name='tools',
            field=models.ManyToManyField(blank=True, null=True, to='api.courtadditionaltool'),
        ),
        migrations.DeleteModel(
            name='BookSetting',
        ),
    ]
