# Generated by Django 5.0.2 on 2024-03-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_booktime_tools_delete_booksetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktime',
            name='event',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='booktime',
            name='with_ball',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
