# Generated by Django 5.0.2 on 2024-03-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0080_alter_booktime_event_alter_booktime_with_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktime',
            name='total_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
